tasks for the fourth lesson
ozoncp/ocp-user-api pull request #1
Opened 2021-05-31 03:28 UTC by andrewstalin

Вместо предложенного функционала по созданию сущностей пачкой, реализовал пакетное извлечение. Для предметной модели пользователя не требуется создание их пачками, а вот извлечение коллекции по идентификаторам, в полне может пригодится. Реализация по семантике аналогична - flusher.

2021-06-01 09:55 UTC, VOOVOOZEL requested changes

2021-06-01 09:55 UTC, VOOVOOZEL commented on internal/extractor/extractor.go
> +const UserNotFoundError NotFoundError = "user not found"
чтобы не реализовывать интерфейс, можно просто указать
var UserNotFoundError = errors.New("user not found")

2021-06-01 09:55 UTC, VOOVOOZEL commented on internal/extractor/extractor.go
> +		for start, end := 0, e.chunkSize; start < len(usersIds); start, end = start+e.chunkSize, end+e.chunkSize {
я бы сделал функцию обертку, чтобы уменьшить условие и вынести логику деления на чанки

к примеру

> func doInChunks(ln int, fn func(start, end int) error) error {
> 	for j := 0; j < ln; j += chunkSize {
> 		end := j + chunkSize
> 		if end > ln {
> 			end = ln
> 		}
> 		err := fn(j, end)
> 		if err != nil {
> 			return err
> 		}
> 	}
> 	return nil
> }

2021-06-01 09:55 UTC, VOOVOOZEL commented on internal/extractor/extractor.go
> +				if errors == nil {
еще неплохо было бы создать свой тип, который будет удовлетворять принципам zero value

2021-06-01 11:17 UTC, andrewstalin commented on internal/extractor/extractor.go
> +				if errors == nil {
Не совсем понял, что имеется ввиду. Тип, возвращаемый GetUsers?

2021-06-02 07:21 UTC, VOOVOOZEL commented on internal/extractor/extractor.go
> +				if errors == nil {
имел ввиду, что можно было  сделать свою структуру, в которой будет lazy инициализация мапы

2021-06-02 07:23 UTC, VOOVOOZEL approved these changes

2021-06-02 10:45 UTC, merged